name: 'Deploy App to S3'

#on: [push] #toutes les branches

on:
  push:
    branches:
      - main #uniquement sur la branche main


jobs:
  deployement: # nom
    runs-on: ubuntu-latest # instance temps
    steps:
    - name: chekout code
      uses: actions/checkout@v4     

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        sudo pip3 install awscli

    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region eu-west-3